ClientSecret: NjkxNDI4NjM4NDczNTg0NjYx.Xnf1GQ.wm47foUe5ducKzOCtjvYEzro0b4
Commands:
  Prefix: 'scruffy> '
DebugMode: true
ExpectedVersion: 4
Introductions:
  Channel: 815001822665637908
  CommonRoles: ["Admin"]
  Enabled: True
  JournalReadPath: sample_journal.csv
  JournalWritePath: sample_journal.csv
  GroupsToRolesMapping:
    G1.1: ["Golemancer"]
    G1.x: ["Golemancer"]
  FuzzyMatchMaxLength: 20
LogFile: scruffy.log
LocalizedMessages:
  Join.Prompt: >
    CzeÅ›Ä‡!

    Jestem bot Scruffy i witam CiÄ™ na serwerze Matematyki dla Ciekawych Åšwiata!

    Na poczÄ…tek proszÄ™, Å¼ebyÅ› na kanale **ğŸ¤przedstaw-siÄ™** napisaÅ‚(a) swoje `ImiÄ™, Nazwisko` (np. "Geralt, z Rivii"); to pozwoli mi przypisaÄ‡ ciÄ™ do odpowienich grup na serwerze.
    NastÄ™pnie przeczytaj regulamin na kanale "ğŸ“œregulamin".

  Introduction.NickUsedError: >
    Zdaje siÄ™, Å¼e juÅ¼ mi siÄ™ przedstawiÅ‚eÅ›(aÅ›) wczeÅ›niej. JeÅ¼eli nie, to coÅ› nie zadziaÅ‚aÅ‚o i skontaktuj siÄ™, proszÄ™, z prowadzÄ…cymi zajÄ™cia.

  Introduction.NotInJournal: >
    Niestety nie mogÄ™ znaleÅºÄ‡ CiÄ™ w dzinenniku.

    SprawdÅº, proszÄ™, czy nie popeÅ‚niÅ‚eÅ›(aÅ›) bÅ‚Ä™du wpisujÄ…c swoje imiÄ™ i nazwisko. JeÅ¼eli tak, wpisz je jeszcze raz, poprawnie, na kanale powitalnym. W przeciwnym wypadku skontaktuj siÄ™ z prowadzÄ…cymi.

  Introduction.Success: >
    Witaj, {first_name}! JesteÅ› w grupie {group}, wiÄ™c przypisaÅ‚em Ci role: {roles_list}.

    Dobrej zabawy na zajÄ™ciach!